import Head from "next/head";
import Banner from "../components/banner/banner";
import NavBar from "../components/nav/navbar";
import SectionCards from "../components/card/section-cards";
import { getPopularVideos, getVideos } from "../lib/videos";
import { magic } from '../lib/magic-client';
import { useEffect, useState } from 'react';
import { useRouter } from "next/router";
import Image from 'next/image';
 



export async function getServerSideProps() {
  const disneyVideos = await getVideos(
    'disney trailer'
  );
  const comedyVideos = await getVideos(
    'comdey movies'
  );
  const codingVideos = await getVideos(
    'coding'
  );
  const popularVideos = await getPopularVideos();

  
  return { props: JSON.parse(JSON.stringify({ disneyVideos, comedyVideos, codingVideos, popularVideos})), };
  };



export default function Home({disneyVideos, comedyVideos, codingVideos, popularVideos}) {

  const router = useRouter();
  const [isLoggedIn, setIsLoggedIn] = useState(false);

  useEffect( ()  => {
    async function fetchEmailData() {
      try {
        const isEmail = await magic.user.isLoggedIn();
        if (!isEmail) { 
          router.push("/login");
          console.log('isLoggedIn');
          setIsLoggedIn(false);
        } else {
          setIsLoggedIn(true);
        }
      } catch (error) {
        // Handle errors if required!
        console.error('Error getting email data', error);
      }
    }
    fetchEmailData();
  }, []);


  return (
    <div>
      <Head>
        <title>Netflix | SDB</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      { !isLoggedIn && (
        <div className="flex items-center justify-center h-screen w-screen animate-pulse">
          <Image
              src={"/static/netflixLogo.svg"}
              alt="Netflix logo"
              width="300px"
              height="100%"
            />
        </div>
      )}

      { isLoggedIn && (
      <>
      <NavBar/>

      <div className="mb-16">
        <Banner
          title="A movie name"
          subtitle="A movie subtitle"
          imgUrl="/static/avengerslandscape.jpg"
        />
      </div>

      <SectionCards title="Disney" videos={disneyVideos} size="portrait" />
      <SectionCards title="Comedy" videos={comedyVideos} size="landscape" />
      <SectionCards title="Learning" videos={codingVideos} size="square" />
      <SectionCards title="Popular" videos={popularVideos} size="landscape" />
      </>

      )}
    </div>
  );
}
