import Head from "next/head";
import Banner from "../components/banner/banner";
import NavBar from "../components/nav/navbar";
import Card from "../components/card/card";
import SectionCards from "../components/card/section-cards";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Netflix | SDB</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar username="sdbxsdb" />

      <div className="mb-16">
        <Banner
          title="A movie name"
          subtitle="A movie subtitle"
          imgUrl="/static/avengerslandscape.jpg"
        />
        <div className="w-full absolute bottom-36 h-24 bg-gradient-to-t from-black40 via-black40 "></div>
      </div>

      <SectionCards title='Disney'/>


    </div>
  );
}
